### PR TITLE
Fix error unlocking a folder when previously deleting the metadata file

### LINKED ISSUE #171: Error on unlock
After delete last file on directory E2ee and send an unlock return error 404

@er-vin @tobiasKaminsky who can test it ?

### PR DESCRIPTION
**Pull request by georgehrke**
fixes #171

### CODE REVIEW

**Comment by marinofaggiana** [comment]
@georgehrke after DELETE metadata now return:

        {"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Solo il proprietario pu\u00f2 eliminare il file dei metadati"},"data":[]}}

**Comment by georgehrke** [comment]
@marinofaggiana How to reproduce that error message?

**Comment by marinofaggiana** [comment]
Simple @georgehrke 
1 - create folder and set as E2EE

2 - lock
3 - upload a file, so store the first e new Metadata
4- unlock

5 - lock
6 - delete file
7 - now in folder don't exists anything file so I send a ocs/v2.php/apps/end_to_end_encryption/api/v1/meta-data/fileID bla bla with method DELETE
8 - return the error
9 - unlock  return error

**Comment by marinofaggiana** [comment]
@georgehrke more Note:

- the point 7 : the endpoint remove the Metadata, but is errata the response with error 403
- the point 9 : as point 7, the end point remove the lock but response with error 403

**Comment by tobiasKaminsky** [comment]
> 7 - now in folder don't exists anything file so I send a ocs/v2.php/apps/end_to_end_encryption/api/v1/meta-data/fileID bla bla with method DELETE

For v2 with sharing you will not be allowed to do this, as in the metadata file will be the information if and to whom a folder is shared
So you can do this for now (v1) or choose to not do it all.

(in my opinion it is not needed at all. Once users deletes a folder or un-encrypt a folder the metadata will be deleted anyways)

**Comment by georgehrke** [comment]
@marinofaggiana Did you try this again with a clean clone of this branch, etc?

**Comment by georgehrke** [comment]
Rebased

**Comment by tobiasKaminsky** [comment]
:+1:

**Pull request merged**
