### PR TITLE
Move codecov to action

### PR DESCRIPTION
**Pull request by tobiasKaminsky**
Signed-off-by: tobiasKaminsky <tobias@kaminsky.me>

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
Codecov fails as php unit does not find any tests and thus there is nothing to upload.

**Comment by tobiasKaminsky** [comment]
Codecov works :+1: 
No idea about the other errors…🤷

**Comment by nickvergessen** [comment]
Rebasing

**Pull request merged**
