### PR TITLE
Update stable23 target versions

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Review by PVince81 — APPROVED** [review]
:+1:

**Comment by eibex** [comment]
Is there any issue that needs testing to release this to the app store? (e.g. pgsql + php8)
#273

**Comment by gessel** [comment]
It would be very helpful to get 1.9.1 into the app store.

**Comment by ItsMeOnceMore** [comment]
Hi, new on Github and on Nextcloud.
Indeed, I installed NC on my web hosting service because of it advertising E2EE...  :-D

I am unable to find a (F)OSS and privacy respecting solution that allows me to E2E encrypt and sync files, contacts and calendars. If NextCloud would manage this, I would gladly abandon the default contacts and calendar apps on my devices. Unluckily there are no calendar/contacts apps for iOS, and the web interface is too inconvenient for this...

**Pull request merged**
