### PR TITLE
refactor: Migrate to nextcloud-vue v8 and dialogs v5

### PR DESCRIPTION
**Pull request by susnux**
* Resolves https://github.com/nextcloud/end_to_end_encryption/issues/674

Modernize the code by using latest versions of our libraries, this also fixes some visual issues with nextcloud 30.

### CODE REVIEW

**Review by AndyScherzinger — APPROVED** [review]
LGTM 👍

**Comment by susnux** [comment]
> NPM build Expected — Waiting for status to be reported 

This will never turn green as that CI does not exist anymore, can someone maybe remove that from the required list?

**Comment by AndyScherzinger** [comment]
Force merged since I lack the knowledge on how to remove the required state of the obsolete GH action.

**Pull request merged**
