### PR TITLE
Update stable22 target versions

### PR DESCRIPTION
**Pull request by nickvergessen**
Signed-off-by: Joas Schilling <coding@schilljs.com>

### CODE REVIEW

**Comment by AndyScherzinger** [comment]
@nickvergessen is this all we need to to do get a v22 compatible release?

**Comment by nickvergessen** [comment]
Maybe, maybe not. It will run ci against it again, but whether or not that means the app works is up to the maintainer

**Comment by tobiasKaminsky** [comment]
Test against stable 22 worked 👍 : https://drone.nextcloud.com/nextcloud/android/2258/1/2

**Review by AndyScherzinger — APPROVED** [review]
works and Android CI builds are successfully testing against v22 👍

**Pull request merged**
